In [197]:
import numpy as np
import pandas as pd
from scipy.stats import norm
from scipy.optimize import least_squares

In [198]:
swaption_data = pd.read_csv("../data/processed/swaption_data_clean.csv")

In [199]:
swaption_data.head()

,Expiry,Tenor,Forward,Annuity,Offset,Straddle,Strangle,RiskReversal,Payer,Receiver,Strike_Payer,Strike_Receiver,T_expiry
0,3m,1y,0.034156,0.958110,0.0025,20,10,-2,4.0,6.0,0.036656,0.031656,0.25
1,6m,1y,0.033345,0.950620,0.0050,31,13,-3,5.0,8.0,0.038345,0.028345,0.50
2,1y,1y,0.033189,0.934966,0.0100,50,18,-3,7.5,10.5,0.043189,0.023189,1.00
3,2y,1y,0.034962,0.904361,0.0100,78,42,1,21.5,20.5,0.044962,0.024962,2.00
4,3y,1y,0.036630,0.964664,0.0150,96,46,3,24.5,21.5,0.051630,0.021630,3.00

In [200]:
swaption_data['Straddle'] = swaption_data['Straddle'] / 10000
swaption_data['Strangle'] = swaption_data['Strangle'] / 10000
swaption_data['RiskReversal'] = swaption_data['RiskReversal'] / 10000
swaption_data['Payer'] = swaption_data['Payer'] / 10000
swaption_data['Receiver'] = swaption_data['Receiver'] / 10000

In [201]:
swaption_data.head()

,Expiry,Tenor,Forward,Annuity,Offset,Straddle,Strangle,RiskReversal,Payer,Receiver,Strike_Payer,Strike_Receiver,T_expiry
0,3m,1y,0.034156,0.958110,0.0025,0.0020,0.0010,-0.0002,0.00040,0.00060,0.036656,0.031656,0.25
1,6m,1y,0.033345,0.950620,0.0050,0.0031,0.0013,-0.0003,0.00050,0.00080,0.038345,0.028345,0.50
2,1y,1y,0.033189,0.934966,0.0100,0.0050,0.0018,-0.0003,0.00075,0.00105,0.043189,0.023189,1.00
3,2y,1y,0.034962,0.904361,0.0100,0.0078,0.0042,0.0001,0.00215,0.00205,0.044962,0.024962,2.00
4,3y,1y,0.036630,0.964664,0.0150,0.0096,0.0046,0.0003,0.00245,0.00215,0.051630,0.021630,3.00

## Calibrating one swaption at a time using SABR model

In [202]:
def calculate_sabr_normal_vol(F, K, T, alpha, rho, nu):
    if F == K:
        # ATM Case (K = F)
        sigma_n = alpha * (1 + ((2 - 3 * rho**2) / 24 * nu**2) * T)
    else:
        # OTM Case (K != F)
        zeta = (nu / alpha) * (F - K)
        
        # x_hat(zeta) calculation
        term = np.sqrt(1 - 2 * rho * zeta + zeta**2)
        x_hat_zeta = np.log((term + zeta - rho) / (1 - rho))
        
        # Hagan Normal Volatility Expansion
        sigma_n = alpha * (zeta / x_hat_zeta) * (1 + ((2 - 3 * rho**2) / 24 * nu**2) * T)
        
    return sigma_n

def bachelier_payer_price(F, K, T, sigma_n, annuity):
    d = (F - K) / (sigma_n * np.sqrt(T))
    price = annuity * ((F - K) * norm.cdf(d) + sigma_n * np.sqrt(T) * norm.pdf(d))
    return price

def bachelier_receiver_price(F, K, T, sigma_n, annuity):
    d = (F - K) / (sigma_n * np.sqrt(T))
    price = annuity * ((K - F) * norm.cdf(-d) + sigma_n * np.sqrt(T) * norm.pdf(d))
    return price

In [203]:
def calculate_model_prices(expiry, tenor, alpha, rho, nu):
    # Select row of swaption_data where expiry and tenor match
    swaption_data_row = swaption_data[(swaption_data['Expiry'] == expiry) & (swaption_data['Tenor'] == tenor)]

    fwd = swaption_data_row['Forward'].iloc[0]
    expiry_t = swaption_data_row['T_expiry'].iloc[0]
    annuity = swaption_data_row['Annuity'].iloc[0]

    strike_payer = swaption_data_row['Strike_Payer'].iloc[0]
    strike_receiver = swaption_data_row['Strike_Receiver'].iloc[0]
    
    # Calculating model vols
    atm_vol = calculate_sabr_normal_vol(fwd, fwd, expiry_t, alpha, rho, nu)
    payer_vol = calculate_sabr_normal_vol(fwd, strike_payer, expiry_t, alpha, rho, nu)
    receiver_vol = calculate_sabr_normal_vol(fwd, strike_receiver, expiry_t, alpha, rho, nu)

    # Calculating model prices
    atm_straddle_model_price = 2 * annuity * (atm_vol * np.sqrt(expiry_t)/np.sqrt(2*np.pi))
    payer_model_price = bachelier_payer_price(fwd, strike_payer, expiry_t, payer_vol, annuity)
    receiver_model_price = bachelier_receiver_price(fwd, strike_receiver, expiry_t, receiver_vol, annuity)
    
    return np.array([atm_straddle_model_price, payer_model_price, receiver_model_price])

In [204]:
def get_market_prices(expiry, tenor):
    swaption_data_row = swaption_data[(swaption_data['Expiry'] == expiry) & (swaption_data['Tenor'] == tenor)]
    return np.array([swaption_data_row['Straddle'].iloc[0], swaption_data_row['Payer'].iloc[0], swaption_data_row['Receiver'].iloc[0]])

In [205]:
def residuals(params, expiry, tenor):

    model_prices = calculate_model_prices(expiry, tenor, params[0], params[1], params[2])
    market_prices = get_market_prices(expiry, tenor)

    return model_prices - market_prices

In [206]:
# Loop through each row in the swaption_data DataFrame
for index, row in swaption_data.iterrows():
    expiry = row['Expiry']
    tenor = row['Tenor']

    # Initial Guesses
    initial_params = [0.00619, 0.01, 0.5]

    # Bounds: ([min_alpha, min_rho, min_nu], [max_alpha, max_rho, max_nu])
    lower_bounds = [0.0001, -0.999, 0.0001]
    upper_bounds = [0.5, 0.999, 2.0]

    # Execution
    result = least_squares(
        residuals, 
        initial_params, 
        bounds=(lower_bounds, upper_bounds),
        args=(expiry, tenor)
    )

    swaption_data.loc[(swaption_data['Expiry'] == expiry) & (swaption_data['Tenor'] == tenor), ['alpha', 'rho', 'nu']] = result.x

In [207]:
swaption_data

,Expiry,Tenor,Forward,Annuity,Offset,Straddle,Strangle,RiskReversal,Payer,Receiver,Strike_Payer,Strike_Receiver,T_expiry,alpha,rho,nu
0,3m,1y,0.034156,0.958110,0.0025,0.0020,0.0010,-0.0002,0.00040,0.00060,0.036656,0.031656,0.25,0.005122,-0.284552,1.999831
1,6m,1y,0.033345,0.950620,0.0050,0.0031,0.0013,-0.0003,0.00050,0.00080,0.038345,0.028345,0.50,0.005097,-0.241430,2.000000
2,1y,1y,0.033189,0.934966,0.0100,0.0050,0.0018,-0.0003,0.00075,0.00105,0.043189,0.023189,1.00,0.005648,-0.157938,1.525693
3,2y,1y,0.034962,0.904361,0.0100,0.0078,0.0042,0.0001,0.00215,0.00205,0.044962,0.024962,2.00,0.006058,0.029616,1.253743
4,3y,1y,0.036630,0.964664,0.0150,0.0096,0.0046,0.0003,0.00245,0.00215,0.051630,0.021630,3.00,0.005781,0.072302,0.995169
5,5y,1y,0.039854,0.816361,0.0200,0.0118,0.0056,0.0006,0.00310,0.00250,0.059854,0.019854,5.00,0.006584,0.120868,0.752189
6,10y,1y,0.046440,0.689481,0.0200,0.0135,0.0081,0.0007,0.00440,0.00370,0.066440,0.026440,10.00,0.005980,0.115446,0.603699
7,3m,2y,0.033930,1.885189,0.0025,0.0046,0.0026,-0.0002,0.00120,0.00140,0.036430,0.031430,0.25,0.005970,-0.123016,2.000000
8,6m,2y,0.033777,1.869398,0.0050,0.0070,0.0034,-0.0003,0.00155,0.00185,0.038777,0.028777,0.50,0.005841,-0.100897,2.000000
9,1y,2y,0.034062,1.837582,0.0100,0.0107,0.0042,-0.0004,0.00190,0.00230,0.044062,0.024062,1.00,0.006077,-0.095000,1.563174
10,2y,2y,0.035778,1.776083,0.0100,0.0157,0.0085,0.0002,0.00435,0.00415,0.045778,0.025778,2.00,0.006213,0.029561,1.252095
11,3y,2y,0.037383,1.893191,0.0150,0.0189,0.0091,0.0006,0.00485,0.00425,0.052383,0.022383,3.00,0.005794,0.073283,0.997809
12,5y,2y,0.040586,1.599756,0.0200,0.0231,0.0111,0.0011,0.00610,0.00500,0.060586,0.020586,5.00,0.006551,0.112273,0.759034
13,10y,2y,0.046443,1.348358,0.0200,0.0261,0.0157,0.0013,0.00850,0.00720,0.066443,0.026443,10.00,0.005899,0.110316,0.606083
14,3m,5y,0.035673,4.465157,0.0025,0.0120,0.0073,-0.0003,0.00350,0.00380,0.038173,0.033173,0.25,0.006596,-0.071210,2.000000
15,6m,5y,0.035842,4.424662,0.0050,0.0175,0.0087,-0.0003,0.00420,0.00450,0.040842,0.030842,0.50,0.006157,-0.040532,2.000000
16,1y,5y,0.036434,4.343870,0.0100,0.0258,0.0100,-0.0001,0.00495,0.00505,0.046434,0.026434,1.00,0.006219,-0.009982,1.537421
17,2y,5y,0.038065,4.189560,0.0100,0.0368,0.0199,0.0008,0.01035,0.00955,0.048065,0.028065,2.00,0.006174,0.050364,1.253498
18,3y,5y,0.039589,4.456967,0.0150,0.0441,0.0209,0.0016,0.01125,0.00965,0.054589,0.024589,3.00,0.005764,0.084377,0.989593
19,5y,5y,0.042365,3.754159,0.0200,0.0534,0.0252,0.0031,0.01415,0.01105,0.062365,0.022365,5.00,0.006484,0.137807,0.753201
20,10y,5y,0.047273,3.147409,0.0200,0.0598,0.0358,0.0043,0.02005,0.01575,0.067273,0.027273,10.00,0.005807,0.158506,0.608418
21,3m,10y,0.038835,8.083369,0.0025,0.0212,0.0126,-0.0001,0.00625,0.00635,0.041335,0.036335,0.25,0.006420,-0.013282,2.000000
22,6m,10y,0.039072,8.004416,0.0050,0.0313,0.0154,0.0001,0.00775,0.00765,0.044072,0.034072,0.50,0.006080,0.007582,2.000000
23,1y,10y,0.039689,7.847245,0.0100,0.0463,0.0180,0.0005,0.00925,0.00875,0.049689,0.029689,1.00,0.006170,0.027713,1.543987
24,2y,10y,0.041040,7.552477,0.0100,0.0653,0.0347,0.0014,0.01805,0.01665,0.051040,0.031040,2.00,0.006105,0.050018,1.239300
25,3y,10y,0.042358,8.016518,0.0150,0.0778,0.0362,0.0026,0.01940,0.01680,0.057358,0.027358,3.00,0.005670,0.078265,0.981290
26,5y,10y,0.044542,6.732230,0.0200,0.0932,0.0429,0.0046,0.02375,0.01915,0.064542,0.024542,5.00,0.006331,0.118265,0.743632
27,10y,10y,0.047215,5.647362,0.0200,0.1034,0.0600,0.0070,0.03350,0.02650,0.067215,0.027215,10.00,0.005646,0.150789,0.595354
28,3m,30y,0.041940,16.737080,0.0025,0.0429,0.0253,0.0000,0.01265,0.01265,0.044440,0.039440,0.25,0.006277,0.000039,2.000000
29,6m,30y,0.041992,16.582876,0.0050,0.0631,0.0307,0.0002,0.01545,0.01525,0.046992,0.036992,0.50,0.005917,0.007507,2.000000
30,1y,30y,0.042166,16.273381,0.0100,0.0928,0.0350,0.0007,0.01785,0.01715,0.052166,0.032166,1.00,0.005981,0.019576,1.530229
31,2y,30y,0.042565,15.692615,0.0100,0.1295,0.0675,0.0031,0.03530,0.03220,0.052565,0.032565,2.00,0.005839,0.055724,1.233826
32,3y,30y,0.042880,16.703074,0.0150,0.1534,0.0693,0.0051,0.03720,0.03210,0.057880,0.027880,3.00,0.005380,0.078317,0.974381
33,5y,30y,0.043248,14.117172,0.0200,0.1824,0.0812,0.0089,0.04505,0.03615,0.063248,0.023248,5.00,0.005921,0.117339,0.739483
34,10y,30y,0.042633,12.086852,0.0200,0.2034,0.1143,0.0152,0.06475,0.04955,0.062633,0.022633,10.00,0.005220,0.165696,0.589617

In [208]:
# Save swaption_data to csv
swaption_data.to_csv("../data/processed/swaption_data_with_params.csv", index=False)